#Item in hand is not item
iteminhand: "Take item in your hand"
#Rename success
# {OLDNAME} - item old name
# {NEWNAME} - item new name
rename-message: "You have successfully renamed the item to {NEWNAME}"
#If the player has not entered a name
empty-name: "Please, enter name"

#Command description
cmd-description: "RenameUI"
#Command usage
cmd-usage: "/rename"

#Form title
title: "RenameUI"
#Form description
description: "Input the name you want to give your item"
#Form input
input: ""
#Form sub-input
sub-input: "Here your name"
